---
title: "Resume"
toc-depth: 4
---

Team leader of the computational neuroscience team at the institute of
neurodegenerative diseases. Co‐founder and editor in chief of
[ReScience C] and [Rescience X], editor for [PeerJ Computer Science],
review editor for [Frontiers in Neurobotics], [Frontiers in
Neuroscience], [Frontiers in Psychology], member of the [COSO
Logiciel] (Software and Source Codes College), member of the [COFIS]
(Ofis Advisory Board), co-funder and member of the [FRRN] (French National
Reproducibility Network) advisory board.

Former elected member of the national Inria evaluation committee,
vice‐head of the Mnemosyne project, member of the Open Access
Scholarly Publishers Association. I have directed 16 Phd Students, 4
post‐docs, 4 enginerrs, ≈30 master students, reviewed and examined ≈40
PhD thesis and participated in more than 20 hiring committees (tenured
position). I'm regularly teaching cognitive science, computational
neuroscience, numerical computation and scientific visualization at
university, doctoral schools and summer schools. I've also published
several resources about scientific computation, scientific
visualization and machine learning.


### History

::: {.history}
+---------------+-------------------------------------------------------------------+
| 2021 - ...    | Director of Research at ([Inria])<br>                             |
|               | Vice-head of the [Hypermondes] association                        |
+---------------+-------------------------------------------------------------------+
| 2020 - ...    | Head of the Computational Neuroscience team ([IMN])<br>           |
|               | Vice-head of the [Mnemosyne] team-project ([Inria Bordeaux])<br>  |
|               | Member of the DART team ([LaBRI])                                 |
+---------------+-------------------------------------------------------------------+
| 2013 - 2020   | Researcher (tenured) at [Inria Bordeaux] <br>                     |
|               | Vice-head of the [Mnemosyne] team-project<br>                     |
|               | Member of the [Institute of Neurodegenerative Diseases]<br>       |
|               | Member of the [LaBRI] laboratory                                  |
+---------------+-------------------------------------------------------------------+
| 2011          | Habilitation, [Université Nancy 2] <br>                           |
|               | *Fondements biologiques pour le calcul distribué*                 |
+---------------+-------------------------------------------------------------------+
| 2002 - 2013   | Researcher (tenured) at [Inria Nancy]<br>                         |
|               | Member of the Cortex team-project<br>                             |
|               | Member of the [Loria] laboratory                                  |
+---------------+-------------------------------------------------------------------+
| 2000 - 2002   | Associate Researcher at [Colorado University, Boulder]<br>        |
|               | Member of the O’Reilly [Cognitive Psychology laboratory]<br>      |
+---------------+-------------------------------------------------------------------+
| 1997 - 2000   | Ph.D. in Computer Science, [Université Henri Poincaré]<br>        |
|               | *Modèles de mémoires pour la navigation autonome*                 |
+---------------+-------------------------------------------------------------------+
| *(1996-1997)* | *Military service in the naval air force*                         |
+---------------+-------------------------------------------------------------------+
| 1993 - 1996   | Engineer [Telecom Nancy] (ex ESIAL) <br>                          |
|               | DEA (Master) in Computer Science, [Université Nancy 1]            |
+---------------+-------------------------------------------------------------------+
:::

[Inria]: https://www.inria.fr/en/
[Inria Nancy]: https://www.inria.fr/en/inria-centre-universite-lorraine
[Inria Bordeaux]: http://www.inria.fr/en/centre/bordeaux

[Université Henri Poincaré]: https://www.univ-lorraine.fr/
[Telecom Nancy]: https://telecomnancy.univ-lorraine.fr/
[Université Nancy 1]: https://www.univ-lorraine.fr/
[Université Nancy 2]: https://www.univ-lorraine.fr/
[Hypermondes]: https://hypermondes.fr
[Institute of Neurodegenerative Diseases]: http://www.imn-bordeaux.org/en/
[Mnemosyne]: https://www.inria.fr/equipes/mnemosyne
[Inria Nancy Grand‐Est]: http://www.inria.fr/en/centre/nancy
[LaBRI]: http://www.labri.fr/
[Loria]: http://www.loria.fr/en
[Institute of Neurodegenerative Diseases]: http://www.imn-bordeaux.org/en/
[IMN]: http://www.imn-bordeaux.org/en/
[University of Bordeaux]: http://www.u-bordeaux.com
[Colorado University, Boulder]: https://www.colorado.edu
[Labex Brain]: https://brain.labex.u-bordeaux.fr/
[Cognitive Psychology laboratory]: https://www.colorado.edu/faculty/oreilly/
[ReScience C]: https://rescience.github.io
[ReScience X]: http://rescience.org/x
[PeerJ Computer Science]: https://peerj.com/
[Frontiers in Neurobotics]: https://www.frontiersin.org/journals/neurorobotics#
[Frontiers in Neuroscience]: https://www.frontiersin.org/journals/neuroscience#
[Frontiers in Psychology]: https://www.frontiersin.org/journals/psychology#
[COSO Logiciel]: https://www.ouvrirlascience.fr/college-codes-sources-et-logiciels/
[COFIS]: https://www.ofis-france.fr/ofis-advisory-board/
[FRRN]: http://www.recherche-reproductible.fr/


<!-- ## Main collaborators -->

<!-- [Thomas Boraud](https://www.bordeaux-neurocampus.fr/en/staff/thomas-boraud/) -->
<!--   (Institute of Neurodegenerative Diseases, Bordeaux)   -->
<!-- [Arthur Leblois](https://www.bordeaux-neurocampus.fr/staff/arthur-leblois/) -->
<!--   (Institute of Neurodegenerative Diseases, Bordeaux)    -->
<!-- [Konrad Hinsen](http://khinsen.net/) -->
<!--   (Centre de Biophysique Moléculaire, Orléans)   -->
<!-- [Etienne Roesch](http://etienneroes.ch/) -->
<!--   (University of Reading, Reading, UK)   -->
<!-- [Frédéric Alexandre](http://www.labri.fr/perso/falexand/) -->
<!--   (Inria Bordeaux Sud-Ouest)   -->

## People

### PhD students {.visually-hidden}
### Post-doc and engineers {.visually-hidden}

::: {layout-ncol=2}

### PhD students

**Yousra Ouazzani Touhami** 2025-2028  
**Mélanie Romano** 2025-2028  
**Maeva Andriantsoamberomanga** 2022-2025  
[Naomi Chaix-Echel](https://theses.hal.science/tel-04849313v1) (PhD) 2021-2024  
[Nikolaos Vardalakis](https://theses.fr/2024BORD0055) (PhD) 2020-2024  
[Fjola Hyseni](https://theses.fr/2023BORD0351) (PhD,MD) 2020-2023    
[Snighda Dagar](https://www.theses.fr/2023BORD0106) (PhD) 2019-2023  
[Remya Sankar](https://www.theses.fr/2022BORD0441) (PhD) 2018-2022  
[Anthony Strock](https://www.theses.fr/2020BORD0195) (PhD) 2017-2020  
[Ikram Chraibi Kaadoud](https://www.theses.fr/2018BORD0032) (PhD) 2015-1018  
[Aurélien Nioche](https://www.theses.fr/2018SORUS361) (PhD) 2014-2018  
[Meropi Topalidou](https://www.theses.fr/2016BORD0174) (PhD) 2013-2016  
[Georgios Detorakis](https://www.theses.fr/2013LORR0140) (PhD) 2010-2013  
[Wahiba Taouali](https://www.theses.fr/2012LORR0105) (PhD) 2009-2012  
[Jérémy Fix](https://www.theses.fr/2008NAN10052) (PhD) 2005-2008  
[Julien Vitay](https://www.theses.fr/2006NAN10052) (PhD) 2002-2006  

### Post-doc and engineers

[Roshni Borse](https://www.linkedin.com/in/rborse) 2024-2025  
[Fabien Benureau](https://fabien.benureau.com/) 2016-1017  
[Zhor Ramdane-Cherif](https://dev-dcac.univ-lorraine.fr/fr/ramdane-cherif-zhor) 2005-2006  
[Rémi Coulom](https://www.kayufu.com/) 2003-2004  
Alistair Bray 1998-2000  

:::

### Interns

**Yves Apriou** (2025, Bordeaux)
**Héloise Troublé** (2024, ENS Rennes)
**Pierre Schmittbuhl** (2024, ENS Lyon)
**Gautham Venugopal** (2023, IIIT Hyderabad, India)
**Victor Leroy** (2022, ENST, Bordeaux)
**Rebecca Lafont** (2022, Bordeaux INP)
**Bhushan Rugbursing** (2021, Médecine/Science, Bordeaux),
**Karen Sobriel** (2021, Université de Nantes),
**Quentin Lanneau** (2021, ENSEIRB, Bordeaux),
**Kepa Labescau** (2020, Médecine/Science, Bordeaux),
**Dimitri Lerévérend** (2020, ENS Rennes),
**Nicolas Thou** (2020, ENSEIRB, Bordeaux),
**Adrien Tétar** (2019, ESIEE, Paris),
**Gabriel Gouraud** (2019, Polytechnique, Saclay),
**Théophile Boraud** (2018, Univ. Warwick, UK),
**Edwige Cyffers** (2018, ENS, Lyon),
**Basile Garcia** (2018, Univ. Bordeaux, Bordeaux),
**Remya Sankar** (2017, IIIT Hyderabad, India),
**Anthony Strock** (2017, ENS, Rennes),
**Sabyasachi Shivkumar** (2016, IIIT Madras, India),
**Barghav teja Nallapu** (2015, IIIT Hyderabad, Indoa),
**Aurélien Marie** (2015, Univ. Bordeaux, Bordeaux),
**Hima Mehta** (2014, IIIT Hyderabad, Inde),
**Meropi Topalidou** (2013, Univ. Crete, Greece),
**Zoé Barbanneau** (2011, Ecole Estienne, Paris),
**Wahiba Taouali** (2009, Ecole des Mines, Nancy),
**Andrew Szabados** (2008, Univ. Jussieu, Paris),
**Johnatan Gall** (2006, Supélec, Metz),
**Jérémy Fix** (2003, Supélec, Metz),
**Yoann Dieu** (2003, Univ. Strasbourg, Strasbourg),
**Julien Vitay** (2002, Supélec, Rennes).

